# Generated by Django 4.2.5 on 2023-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0010_customuser_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
