# Generated by Django 4.2.5 on 2023-10-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='price_Was',
        ),
        migrations.AddField(
            model_name='product',
            name='percent_Off',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.URLField(),
        ),
    ]
