# Generated by Django 4.2.5 on 2023-10-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0003_rename_discount_product_price_was_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
