# Generated by Django 4.2.5 on 2023-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0005_rename_percent_off_product_percentage_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_was',
            field=models.CharField(max_length=50),
        ),
    ]
