# Generated by Django 4.2.5 on 2023-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0008_alter_product_percentage_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Reviews',
            field=models.CharField(max_length=200),
        ),
    ]
