# Generated by Django 4.2.5 on 2023-10-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0014_cart_cart_item_delete_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City_Product_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.city')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime.product')),
            ],
        ),
    ]
