# Generated by Django 4.2.5 on 2023-10-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0015_city_city_product_relation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
